### PR TITLE
Added components for implmentation of Alexa skills using TotalJS flow.

### PR DESCRIPTION
**Pull request by gravesjohnr**
These can be handy if people want to implement Alexa skills using TotalJS flow.

AlexaRouter - Listens for intents and routes them to other flow components.
AlexaResponse - Responds with SMML messages for Alexa to say.

Demo: https://youtu.be/YBtN4Ky3MLo

### CODE REVIEW

**Comment by molda** [comment]
Hi, that's awesome :+1:
One think i'm not sure is good is that you implemented F.route into the alexarouter. I mean you could simply use httproute component in front of alexarouter. Removing the F.route would make the alexarouter's code much shorter and easier to read and maintain.

I know it takes up less space in the designer but i think that one component should do just one thing (where possible).

Anyways great job :+1:

**Comment by gravesjohnr** [comment]
Ok.  I'll have a look.  I'm still getting used to all the components and which one to use at which times.

Thanks.

**Comment by gravesjohnr** [comment]
I've made the change.  I'll need to update the video, but I think it works fine with putthing the HTTPRouter in front.

**Comment by gravesjohnr** [comment]
image

**Comment by molda** [comment]
Awesome :+1: :+1: 
I've never seen so many outputs :smile: 
I see you are learning pretty fast.

Thank You for Your contribution. Keep it up.

**Pull request merged**
