### PR TITLE
Added websocket component.

### PR DESCRIPTION
**Pull request by gravesjohnr**
This component listens to a websocket and outputs into the flow.

### CODE REVIEW

**Comment by gravesjohnr** [comment]
I'm having issues with building a test file because I don't know of a sample websocket I can use.  Recommendations?

**Comment by petersirka** [comment]
I think that better will be used Total.js WebSocketClient: https://blog.totaljs.com/blogs/news/20171116-total-js-v2-9-0/#new-websocketclient __instead of `html5-websocket` module. I'll look into it today later.

**Comment by molda** [comment]
Hi @gravesjohnr i have got both server and client websocket components already. I finnished them couple days ago just didn't have time to commit. They are implemented using framework's internal classes. 
I'm just testing them and will commit soon.

**Comment by gravesjohnr** [comment]
Oh great!  Even better.  Thanks!.

**Comment by molda** [comment]
@gravesjohnr The WebSocket components are out. Check them out and let me know if you find any issues or something to improve :+1:
#12

**Comment by gravesjohnr** [comment]
THANKS!  I saw that.  I'll have a look.

**Comment by gravesjohnr** [comment]
@molda 

Testing the wsclient works, but the reconfigure doesn't.  It seems you have coded the connect to 'reconnect' without reading the new configured values.  I believe you want to tear down the existing connection, re-read the options and re-establish a new connection on each reconfigure.

I'll test out the wsserver later.

Thanks again for this.

-John

**Comment by molda** [comment]
@gravesjohnr i found the problem. I'll fix it and let you know.

**Comment by molda** [comment]
@gravesjohnr Fixed.

**Comment by gravesjohnr** [comment]
@molda  Confirmed... Works great.  Thanks!

FYI, you might want to eventually remove the console.log message.

**Pull request closed without merging**
